# @format

name: CI BarberAlgo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Verificar projeto
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: barberalgo

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: barberalgo/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Rodar lint
        run: npm run lint

      - name: Gerar build do projeto
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
